
GET  http://localhost:3000/api/post?id=65c49633f174bd3ee4824bf5
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNkODc3YjRjYjAxZWY5MTdkZGFjZCIsImlhdCI6MTcwNzM4NDk0MywiZXhwIjoxNzA3NDcxMzQzfQ.VR2PQLpgeR3M_jhLflQnayaCwqueruk8kPiWC4B4_74

###
POST  http://localhost:3000/api/auth/post
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNkODc3YjRjYjAxZWY5MTdkZGFjZCIsImlhdCI6MTcwNTM3OTA0NSwiZXhwIjoxNzA1NDY1NDQ1fQ.7jtboGh27SsUEVSMqLDtefnA4aFZ4hRshvdmDYn-gTI

{
    "content":"Hello"
}
###
 POST  http://localhost:3000/api/login
Content-Type: application/json

{
    "nickname":"locpham",
    "password":"123456"
}
###

GET http://localhost:3000/api/auth/comment?postId=6597c97b0e29e243fa7d4976
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OGQwOGU3ZDFlNjViYmVhMzIzN2FmZCIsImlhdCI6MTcwNDQyMjI3NiwiZXhwIjoxNzA0NTA4Njc2fQ.50LgL5GkFo5utYNcGY2nFTfchqseH_Z6m7J9RQ9zTO8

{
    "content":"おやすみなさい"
}