
GET  http://localhost:3000/api/post?id=65c49633f174bd3ee4824bf5
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNkODc3YjRjYjAxZWY5MTdkZGFjZCIsImlhdCI6MTcwNzM4NDk0MywiZXhwIjoxNzA3NDcxMzQzfQ.VR2PQLpgeR3M_jhLflQnayaCwqueruk8kPiWC4B4_74

###
GET  http://localhost:3000/api/auth/user
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNkODc3YjRjYjAxZWY5MTdkZGFjZCIsImlhdCI6MTcwOTYyMDIwNiwiZXhwIjoxNzA5NzA2NjA2fQ.oHUljgVSSC7wQXD7mHVN6ZrAzqCqzSWcsANhfQTDLKg

###
POST  http://localhost:3000/api/login
Content-Type: application/json

{
    "nickname":"locpham",
    "password":"123456"
}


###
GET  http://localhost:3000/api/user
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNkODc3YjRjYjAxZWY5MTdkZGFjZCIsImlhdCI6MTcwOTc3MzYxNywiZXhwIjoxNzA5ODYwMDE3fQ.kgrKz2jqBzK1Cs0DQVHbEeWSEPgQFg9zpRCQALG9_3E
###

POST  http://localhost:3000/api/auth/post
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNkODc3YjRjYjAxZWY5MTdkZGFjZCIsImlhdCI6MTcwOTYyMDIwNiwiZXhwIjoxNzA5NzA2NjA2fQ.oHUljgVSSC7wQXD7mHVN6ZrAzqCqzSWcsANhfQTDLKg

{
    "title":"3月5日テスト",
    "content":"3月5日テスト"
}
###

DELETE  http://localhost:3000/api/auth/post?id=65e6dd6b22ed7a41ad6885ca
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNkODc3YjRjYjAxZWY5MTdkZGFjZCIsImlhdCI6MTcwOTYyMDIwNiwiZXhwIjoxNzA5NzA2NjA2fQ.oHUljgVSSC7wQXD7mHVN6ZrAzqCqzSWcsANhfQTDLKg
